name: Reusable Workflow

on:
  workflow_call:
    inputs:
      who-to-greet:
        type: string
        default: 'World'
    outputs:
      current-time:
        description: 'The time when greeting.'
        value: ${{ jobs.reusable-job.outputs.current-time }} 


jobs:
  reusable-job:
    runs-on: ubuntu-latest
    outputs:
      current-time: ${{ steps.time.outputs.time }}
    steps:
      - name: Greet someone
        run: echo 'Hello'
      
      - name: Set time
        id: time
        run: echo "time=$(date)" >> $GITHUB_OUTPUT
